---
- name: 'set os variables'
  include_vars: '{{ item }}'
  with_first_found:
   - '{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version }}.yml'
   - '{{ ansible_distribution | lower }}.yml'
   - '{{ ansible_os_family | lower }}.yml'

- name: 'debian | install lldp'
  include: install-debian.yml
  when: ansible_os_family == 'Debian'
